# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Tools\CMake\bin\cmake.exe

# The command to remove a file.
RM = C:\Tools\CMake\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\Software\Eevee_Software

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\Software\Eevee_Software

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:\Tools\CMake\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\Tools\CMake\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Software\Eevee_Software\CMakeFiles E:\Software\Eevee_Software\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Software\Eevee_Software\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named free_rtos

# Build rule for target.
free_rtos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 free_rtos
.PHONY : free_rtos

# fast build rule for target.
free_rtos/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/build
.PHONY : free_rtos/fast

#=============================================================================
# Target rules for targets named eevee_software

# Build rule for target.
eevee_software: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 eevee_software
.PHONY : eevee_software

# fast build rule for target.
eevee_software/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eevee_software.dir\build.make CMakeFiles/eevee_software.dir/build
.PHONY : eevee_software/fast

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eevee_software.dir\build.make CMakeFiles/eevee_software.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eevee_software.dir\build.make CMakeFiles/eevee_software.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eevee_software.dir\build.make CMakeFiles/eevee_software.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.c.s

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eevee_software.dir\build.make CMakeFiles/eevee_software.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eevee_software.dir\build.make CMakeFiles/eevee_software.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eevee_software.dir\build.make CMakeFiles/eevee_software.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.c.s

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eevee_software.dir\build.make CMakeFiles/eevee_software.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eevee_software.dir\build.make CMakeFiles/eevee_software.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eevee_software.dir\build.make CMakeFiles/eevee_software.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.c.s

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.c.s

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.c.s

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.c.s

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.c.s

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.c.s

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.c.s

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.c.s

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.c.s

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.obj: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.obj

# target to build an object file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.obj
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.obj

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.i: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.i

# target to preprocess a source file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.i
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.i

sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.s: sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.s

# target to generate assembly for a file
sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\free_rtos.dir\build.make CMakeFiles/free_rtos.dir/sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.s
.PHONY : sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... eevee_software
	@echo ... free_rtos
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/Run-time-stats-utils.s
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main.s
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Demo/WIN32-MingW/main_blinky.s
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/croutine.s
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/event_groups.s
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/list.s
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MSVC-MingW/port.s
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/portable/MemMang/heap_5.s
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/queue.s
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/stream_buffer.s
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/tasks.s
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.obj
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.i
	@echo ... sources/eevee/FreeRTOSv202112.00/FreeRTOS/Source/timers.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

